services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      - DB_TYPE=mariadb
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=test
      - DB_USER=root
      - DB_PASSWORD=admin
    depends_on:
      - db
  db:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3308:3306'
volumes:
  db_data:
